#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
import sys, select, termios, tty, time, os, subprocess

if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin)

    rospy.init_node('scale')
    pub = rospy.Publisher('~cmd_vel', Twist, queue_size=5)

    try:
        # get weight

        # bashCommand = "perl usbscale.pl"
        # process = subprocess.Popen("perl /home/cse/catkin_ws/src/navigation/scripts/usbscale.pl".split(), stdout=subprocess.PIPE)
        # weight = process.communicate()[0].strip()
        # print weight
        # print filename

        dircur = os.path.dirname(__file__)
        filename = os.path.join(dircur, 'data.txt')
	print filename
        with open(filename) as f:
            content = f.read()
	    print content
            if (float(content) > 0.1):
                timing = time.time()
                while (time.time() - timing < 2):
                    twist = Twist()
                    twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0
                    twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 1
                    pub.publish(twist)


    finally:
        twist = Twist()
        twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        pub.publish(twist)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
